---
version: "3.8"

services:

  jupyterlab:
    image: jupyterlab-base:3.5.2
    # build:
    #   context: .
    #   dockerfile: base.Dockerfile
    container_name: jupyterlab
    hostname: jupyterlab
    command: jupyterlab
    ports:
      - target: 8890
        published: 8890
        mode: host
    volumes:
      - type: bind
        source: ./data
        target: /workspace
    networks:
      - main-network
    environment:
      # Port to start Jupyter Lab (default: 8888)
      JUPYTERLAB_PORT: 8890
    working_dir: /workspace
    restart: always


networks:
  main-network:
    name: main-network
    external: false
    driver: bridge
    attachable: false
